# Generated by Django 4.1.7 on 2023-05-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_company_name', models.CharField(max_length=50)),
                ('car_name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.png', upload_to='pics')),
                ('car_type', models.CharField(max_length=50)),
                ('rent_per_day', models.IntegerField(default=0)),
            ],
        ),
    ]
